<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-D7FC95S" failures="1" tests="3" name="tests.LoginTest" time="44.726" errors="0" timestamp="2022-10-11T20:37:55 CEST" skipped="2">
  <testcase classname="tests.LoginTest" name="login" time="13.561">
    <skipped/>
  </testcase> <!-- login -->
  <system-out/>
  <testcase classname="tests.LoginTest" name="login" time="14.905">
    <failure message="expected [Sign ou] but found [Sign out]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Sign ou] but found [Sign out]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pages.BasePage.assertStringEquals(BasePage.java:40)
at pages.UserLoggedInPage.verifyLogin(UserLoggedInPage.java:17)
at tests.LoginTest.login(LoginTest.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- login -->
  <system-out/>
  <testcase classname="tests.LoginTest" name="login" time="16.260">
    <skipped/>
  </testcase> <!-- login -->
  <system-out/>
</testsuite> <!-- tests.LoginTest -->
